### ISSUE TITLE
Documentation videos invisible or hard to play after move to webm

### ISSUE THREAD

**Issue by tlambert03** [napari/docs#60]
## 🐛 Bug

napari/napari#4207 converted all of our gifs to webm, in an attempt to stop the bleeding on our LFS bandwidth.  Unfortunately, it seems to have had some bad side effects on usability of the site.

On Chrome 99.0.4844.83 (macOS), it's not very obvious that the movies are anything other than still images.  The mouse doesn't change icon when you hover, clicking does nothing, etc... I had to right click on the image and show controls in order to do anything:

https://user-images.githubusercontent.com/1609449/159525999-344a7fc9-cb35-4d26-b562-40c2fd6091a1.mov

In safari 15.3, I see nothing at all:

<img width="754" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/159526332-d6662798-0698-43fb-b9ba-8a7cce577799.png">

based on caniuse link that @Carreau added in napari/napari#4207: https://caniuse.com/webm ... it appears that I fall in the "3.4%" of unsupported computers because my desktop isn't on big sur or later yet

on firefox, I also had to right click to get anything to play

Given that LFS has so many other issues, and this change wasn't without some unfortunate side effects, I wonder if perhaps we shouldn't consider reverting this one?

**Comment by psobolewskiPhD** [comment]
I'm on Monterrey and also have white boxes where there used to be videos.
Same on my phone.
Common element: Safari
Installed Chrome Version 99.0.4844.74 (Official Build) (arm64)
and the videos are replaced with still images with same behavior as above.

**Comment by Carreau** [comment]
It seem to be just because the html misses the `controls` (and autoplay=true) ? attribute. 
I didn't manage to build the docs with the napari sphinx theme to tried separately in an custom html page.

**Comment by tlambert03** [comment]
yeah, I think that will probably fix the chrome and firefox issues, but probably still leave a number of safari users without an image?

**Comment by Carreau** [comment]
Yeah, I don't know. We can try another format than webm, I'm not particularly attached to it.
(note, we may want to also add `loop=true`)

**Comment by jni** [comment]
Yes, we should use autoplay=true and loop=true, and *possibly* use mp4 instead of webm. I don't want to go back to gif.

**Comment by Carreau** [comment]
napari/napari-sphinx-theme#94 is the best workaround I found.

**Comment by Carreau** [comment]
Here is some attempt at confertign the original gifs to mp4 using this:

```
# https://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line
ls *.gif| cut -f1 -d. | xargs -L1 -I {base} ffmpeg -i {base}.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" {base}.mp4
```

Can you try on safaris see if you still get the white square.:

https://user-images.githubusercontent.com/335567/159936835-fa3512d9-e7f3-4b5f-ae7c-96b86e2487da.mp4


https://user-images.githubusercontent.com/335567/159936855-35e07503-7e21-494a-bc65-4230e196f67d.mp4


https://user-images.githubusercontent.com/335567/159936858-c60870c2-5e4f-4358-8962-c944551d1c52.mp4


https://user-images.githubusercontent.com/335567/159936861-9eb95b80-078b-45c3-871a-290c10ff4056.mp4


https://user-images.githubusercontent.com/335567/159936869-fcc46834-c22a-4651-b757-f997cd9685b8.mp4



https://user-images.githubusercontent.com/335567/159936823-ceec9636-a77f-4af2-8867-fa92b5204023.mp4

**Comment by psobolewskiPhD** [comment]
I get a white square with a play icon in the middle and they work fine when clicked (same as Talley's video in the OP).

**Comment by jni** [comment]
> I get a white square with a play icon in the middle and they work fine when clicked (same as Talley's video in the OP).

In my blog I copied the autoplaying-videos solution from somewhere else (can't remember where), and it includes a little jpg of a video frame inside the tag:

https://github.com/jni/ilovesymposia.com/blob/ee21be8285ddcb32b746d2a1f91c4d1dde1b540c/posts/2019/10/24/introducing-napari-a-fast-n-dimensional-image-viewer-in-python.md?plain=1#L311

I guess some browsers require this for previewing the video?

**Comment by sofroniewn** [comment]
In reviewing napari/napari#4392 it came to my attention that the napari.org videos don't work on my iPhone either, which also isn't the oldest. It would be good to revisit this again and try and get something that works across the latest platforms

**Comment by jni** [comment]
Good-oh. Now that napari/napari#4392 is in, I guess what we want is to convert all the webms to mp4. @Carreau do you think you could tackle this?

**Comment by andy-sweet** [comment]
napari.org should now autoplay, loop, and show controls for videos now on browser/OS combos that support webm+vp8/9. For example, see the video at the top of: https://napari.org/tutorials/annotation/annotate_points.html

I can't see how that would fix the older macOS/safari issues with webm + vp8/9, so this should stay open until we fix that (likely by converting to mp4 + h264/5).

**Comment by psobolewskiPhD** [comment]
Looks good to me, macOS 12.3.1 safari
<img width="745" alt="image" src="https://user-images.githubusercontent.com/76622105/166564006-a1360856-1bb0-45a3-983f-18800649ca79.png">
Getting all the controls is nice!

**Comment by tlambert03** [comment]
just checking in on my open issues.  This one is still there, and our website still doesn't work on safari:

eg: https://napari.org/stable/tutorials/annotation/annotate_points.html
<img width="748" alt="Screen Shot 2022-07-23 at 2 00 53 PM" src="https://user-images.githubusercontent.com/1609449/180617391-558135bf-3307-4e8f-bff3-b40e4b7d1b6f.png">

I do kinda think this is a big deal, but would prefer not to have to fix it myself, since we did have a working website before the change to webm was made.  Anyone still thinking about this?

**Comment by sofroniewn** [comment]
I think we had a recent regression here that @melissawm @codemonkey800 are looking into

**Comment by melissawm** [comment]
Yes - I've found the issue and am in the process of fixing it. This does not involve the webm conversion but the generation of pages for older versions of the website. I should submit a PR for this later today.

**Comment by jni** [comment]
Should be fixed by napari/napari#354, thank you so much @melissawm! @tlambert03 can you check whether the site renders correctly for you now and close this if so?

**Comment by tlambert03** [comment]
Nope, there might have been a link issue there, but the webp support issue is still a thing: 

![image](https://user-images.githubusercontent.com/1609449/181219759-7e61747e-4152-4843-b680-59dc9d375dd1.png)

**Comment by melissawm** [comment]
It looks like that's a browser issue, it works for me on Chrome/android

![Screenshot_2022-07-27-08-54-11-509_com.android.chrome.jpg](https://user-images.githubusercontent.com/3949932/181240820-6867b5da-2168-473f-8ea5-9c08a7d187c6.jpg)

I guess the best solution is to move to mp4 then, unless there's a specific fix for (I'm assuming) Safari.

**Comment by tlambert03** [comment]
Correct, it's a browser issue. See discussion above (this issue is generally discussing browser support for webm)

That last screenshot was on iOS, see @sofroniewn's comment https://github.com/napari/docs/issues/60

**Comment by Carreau** [comment]
Should this be migrated to the docs repo ?

**Comment by Carreau** [comment]
> [psobolewskiPhD](https://github.com/psobolewskiPhD) transferred this issue from napari/napari [1 minute ago](https://github.com/napari/docs/issues/60#event-7891524206)

Thanks !

**Comment by psobolewskiPhD** [comment]
Update: in safari 16.1 on macOS 12.6, the video on page:
https://napari.org/stable/tutorials/annotation/annotate_points.html
works fine.
However, on mobile Safari (iOS 16.02) I get the non-functional video as noted by Talley above.

**Comment by melissawm** [comment]
Can anyone confirm if this is still present?

**Comment by psobolewskiPhD** [comment]
For that same annotation page, I still get the black box with play crossed out on mobile Safari (iOS 17). Seems fine on desktop Safari 16.4.
Homepage (napari.org) is fine.

**Comment by tlambert03** [comment]
the underlying issue is straightforward. it has always been, and remains to be, that webm support on ios is incomplete: https://caniuse.com/?search=webm

this issue won't be fixed until a more ubiquitously supported format is used (like gif, before https://github.com/napari/napari/pull/4207 was done to get around git-lfs issues, before docs were moved to a new site) , or a `<video>` tag with fallback sources is used.  (Now that docs have been moved out to a new repo, you could just add back the gif files)

**Comment by jni** [comment]
Rather than gif we should use an mp4 fallback, which is well supported on iOS, together with a fallback jpg. All three files together will still weigh a fraction of what the gif would, and give a better experience.

**Comment by jni** [comment]
(I suspect that's how I set up the home page.)

**Comment by melissawm** [comment]
What tools do you use to convert webm into mp4?

**Comment by tlambert03** [comment]
ffmpeg is a good video converter.  something like `ffmpeg -i input.webm output.mp4` might do the trick
